apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  labels:
    app: postgres-user
data:
  POSTGRES_DB: user
  POSTGRES_USER: ECC7AE2E763E2305955EC2DCBCC0EA0F5499F6F5
  POSTGRES_PASSWORD: ECC7AE2E763E2305955EC2DCBCC0EA0F5499F6F5