apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 123654789456123654789/ms-hex-arch-golang-k8s-user:v6    
        env:
        - name: DB_HOST
          value: "10.245.68.205"
        - name: DB_PORT
          value: "30831"
        - name: DB_NAME
          value: user 
        - name: DB_USER
          value: ECC7AE2E763E2305955EC2DCBCC0EA0F5499F6F5 
        - name: DB_PASS
          value: ECC7AE2E763E2305955EC2DCBCC0EA0F5499F6F5 
        - name: DB_SSLMOD
          value: disable
        - name: DB_TIMEZONE
          value: Asia/Shanghai
        - name: APP_PORT
          value: :5678 
        - name: APP_SIGNING_KEY
          value: =MHcCAQEEIAh5qA3rmqQQuu0vbKV/+zouz/y/Iy2pLpIcWUSyImSwoAoGCCqGSM49AwEHoUQDQgAEYD54V/vp+54P9DXarYqx4MPcm+HKRIQzNasYSoRQHQ/6S6Ps8tpMcT+KvIIC8W/e9k0W7Cm72M1P9jU7SLf/vg==
        ports:
          - containerPort: 5678